language: php
php:
  - '7.0'
  - '7.1'
addons:
  sonarcloud:
    organization: "wadmiraal-github"
    token:
      secure: "VFAX4S00//GpUUWIWsf2pDs91tHW03fmJuAvHjzyX3/jaVrGbufPNTafYD0I3xOq3DZmWGUk88fAXAbQYA4uLbtZJLhBKipwPsYKWIEcHC89/A9D535cBeaYJ6jJTzWRIEa8peVYmaA0yBOZdBO3ADgYUotCiwc8kiJEFB0/c45KR2ZosfSKE4V4/YnpsqblLrq31sGxZOOHWSbGa7Uine4ACFhmYC3d6pEgxOEvLgbXyfUU+jkEyNj9Gaule3AwWOHDJMEtBFiweGsL0NYza3WekBBpNE91k9xYjSNdlvUZfpOG7/9f9kKskCgYm/LVWAoKIteTCgRYGPIjK/z3bBK9DcqkKUXWNh+B5D9Nd6dsYfVwDsZwnOst+ztu6VSys00eJDjfcf+K0HfjjzCKLN0VYXYJSgYkLSuV+7e2BEsinwVhA7+OcrT0fXAfTXgWd1RoY6PNtLAzH0GP1ApDJOQGofFPgW8yH+qphzh0fl8Tpt8WbNVLulgx9KfCIw2DqWOhBBJt1X/7RN7OTsAscgabF6ipVJ2EZcgoFF6PR4lw+xslBXjf5RaTPhatusbr6y/sT1N/Xf+bilMSMDCeSELlMZ1snJsLoPXyQGbbI7tXvOW12+PXwWxW01GjwAeEfR3aFWSabxBeotNoRjyuVAMtN0bsHrs/ssZjwws/abU="
env:
  - SIMPLETEST_DB=sqlite://testdb.sqlite
install:
  # We need a full Drupal project for our Kernel tests to work. Create a new project.
  - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
  # Drupal 8.4.x has a bug that doesn't allow Kernel tests to use SQLite. Apply a patch that fixes it.
  - cp sqlite-driver-exception.patch drupal/web && cd drupal/web/ && patch -p1 < sqlite-driver-exception.patch && cd -
  # Our code is no longer in the correct place. Copy it over.
  - mkdir -p drupal/web/modules/guernsey && cp -a guernsey* tests templates src config drupal/web/modules/guernsey
  # Update the phpunit.xml.dist file. We want to ignore test coverage for core files.
  - cp travis-ci-phpunit.xml.dist.patch drupal/web/core && cd drupal/web/core && patch -p1 < travis-ci-phpunit.xml.dist.patch && cd -
script:
  - drupal/vendor/bin/phpunit -c drupal/web/core drupal/web/modules/guernsey/tests/ --coverage-clover clover.xml --log-junit junit.log
  - sonar-scanner -Dsonar.sources=drupal/web/modules/guernsey/src -Dsonar.php.tests.reportPath=junit.log -Dsonar.php.coverage.reportPaths=drupal/web/clover.xml
